#+author: https://www.zhihu.com/people/bi-chu-liu-xiang

* 如何组织党组织换届
小伙伴们有没有组织党支部换届的需要，我们近期刚组织了换届，程序完整、资料翔实，现分享给大家。下面是换届大会的主持词，通过主持词就可以完整的了解换届的有关工作，里面涉及到的各种资料附后，供参考：

同志们：

现在召开支部党员大会，大会的主要任务和议程有两项，一是听取和审查上届党支部委员会工作报告；二是选举新一届党支部委员会。今天应到会党员XX名，其中有选举权党员XX名；实到会党员XX名，其中有选举权党员XX名，符合规定人数，可以开会。现在我宣布，XX党支部党员大会开始，全体起立，奏国歌。（建议选用管弦乐合奏的《国歌》，奏第一段即可。待奏《国歌》毕）请坐下！

一、现在进行第一项议程
由我代表上届党支部委员会作工作报告。（待作工作报告毕）

刚才，我代表上届党支部委员会作了工作报告，请同志们审议，有意见请发表。（稍等）没有。下面请有表权的党员对上届党支部委员会的工作报告进行表决，同意上届党支部委员会工作报告的请举手。请放下！不同意的请举手。（环顾会场）没有（或请放下）！弃权的请举手。（环顾会场）没有（或请放下）！一致通过（或同意的超过实到会有表决权党员的半数，通过）！

二、现在进行第二项议程，选举新一届党支部委员会
首先通过选举办法。

由我宣读选举办法（草案）。〔待宣读选举办法（草案）毕〕

请同志们酝酿一下，有意见请发表。（稍等）没有。下面请有表决权的党员进行表决，同意上述选举办法（草案）的请举手。请放下！不同意的请举手。（环顾会场）没有（或请放下）！弃权的请举手。（环顾会场）没有（或请放下）！一致通过（或同意的超过实到会有表决权党员的半数，通过）！

下面通过监票人名单，宣布计票人员名单。

请XXX同志宣读监票人建议名单。（待宣读监票人建议名单毕）

请同志们酝酿一下，有意见请发表。（稍等）没有。下面请有表决权的党员进行表决，同意上述监票人建议名单的请举手。请放下！不同意的请举手。（环顾会场）没有（或请放下）！弃权的请举手。（环顾会场）没有（或请放下）！一致通过（或同意的超过实到会有表决权党员的半数，通过）！

请XXX同志宣布大会的计票人员名单。（待宣布大会的计票人员名单毕）

下面确定下届党支部委员会委员候选人名单。

请XXX同志宣读下届党支部委员会委员候选人建议名单。（待宣读下届党支部委员会委员候选人建议名单毕）

请同志们酝酿一下，有意见请发表。（稍等）没有（或多数党员无不同意见）。

现在开始选举，请监票人员清点人数。（待监票人报告到会人数情况毕）

据监票人报告：这次党员大会应到会有选举权党员15名、因事因病请假 名，实到会有选举权党员 名，符合规定人数，可进行选举。

请监票人检查票箱。（稍停）加封。（特加贴封条或落锁毕）

请计票人领发选票。请各位有选举权党员领到选票后不要急于填写，关于填写方法还要再说一说。（待计票人领发选票毕）

选票已发完，有选举权的党员有没有未拿到选票的？有没有多拿选票的？请检查一下。（待监票人报告领发选票数情况毕）

据监票入报告：领到选票X张，发出选票X张，多余选票X张，多余的选票请予封存。

（讲解选票填写方法和注意事项）

现在请各位有选举权党员填写选票。

选票填写好后，请检查一下，是否符合选举办法的规定？符号是否清楚、准确？有没有超过应选人数？

下面宣布一下投票顺序。投票的顺序是：先监计票人员投票，再请有选举权党员依次投票。

现在开始投票。

请监计票人员投票；

请各位有选举权的党员投票。（待投票毕）

请监计票人员清点票数。（待监票人报告清点票数情况毕）

据监票人报告：实到会有选举权党员X名，发出选票X张，收回选票X张。收回的选票数等于（或少于）投票人数，选举有效！

现在请计票人员在监票人的监督下计票。请同志们原地休息。（待监票人报告计票结果毕）

……

同志们，现在继续开会。

下面请监票人向大会报告计票结果。（待按得票多少为序报告毕）

下面，宣布新当选的委员名单。根据选举办法规定：下列3位同志当选为机关党支部新一届委员会委员，他们是：XXX、XXX、XXX。（待按姓氏笔画为序宣布新一届党支部委员会委员当选名单毕）

同志们，党员大会现在休会。请新当选的党支部委员会委员到 会议室参加党支部委员会第一次全体会议，选举党支部委员会书记并进行其他委员的分工。（待委员会第一次全体会议毕）

……

同志们，党员大会现在复会。由我宣布党支部委员会第一次全体会议选举结果和委员分工情况。（先宣布书记当选人名单，再宣布委员分工情况。待宣布党支部委员会第一次全体会议选举结果和委员分工情况毕）

上述选举结果，将在会后向上级党组织报批，以学院党委批复为准。

下面，请XXX同志代表新一届党支部委员会成员讲话，大家欢迎。（待讲话毕）

下面，请XXX同志代表上级党组织讲话，大家欢迎。（待讲话毕）

同志们，今天的支部党员大会，经过大家的共同努力，已圆满完成了大会的各项任务，现在我宣布：XXX党支部党员大会闭会！

全体起立，奏《国际歌》。（建议选用管弦乐合奏的《国际歌》，奏第一段即可。待奏《国际歌》毕）

散会。

附件：

1、XX支部委员会工作报告。

2、XX支部党员大会选举办法。

3、XX支部党员大会选票。

4、计票人监票人候选人员名单。

5、报告单1：清点到会人数报告单。

6、报告单2：分发选票情况报告单。

7、报告单3：清点选票结果报告单。

8、报告单4：计票结果报告单。

9、新一届党支部书记表态讲话。

有需要相关材料的小伙伴可单独联系我。

* 个人自我检视发言
作者：悟空
链接：https://zhuanlan.zhihu.com/p/389990549
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

根据XX党委关于开展党史学习教育专题组织生活会的部署和要求，我认真学习有关文件材料，并围绕通知明确的四个方面内容，进行了盘点和检视，现从学习的收获、感悟，存在的问题不足以及下一步改进方向三个方面报告如下，请同志们批评指正。一、党史学习教育的收获和感悟7月1日上午，学院党委组织集中观看了庆祝中国共产党成立100周年大会，通过视频直播观看大会盛况，深刻感受到这是一次指引方向、开创未来的历史性盛会。习近平总书记在大会上的重要讲话，立意高远、思想深邃、气势恢弘、催人奋进，具有很强的政治性、思想性、理论性、指导性，是一篇闪耀着马克思主义真理光辉、引领中华民族实现伟大复兴的纲领性讲话。习近平总书记说：“中国人民绝不允许任何外来势力欺负、压迫、奴役我们，谁妄想这样干，必将在14亿多中国人民用血肉筑成的钢铁长城面前碰得头破血流！”，振聋发聩、掷地有声，身为中国共产党的一员，我倍感自豪。同时，站在“两个一百年”历史交汇点上，我辈也当感受到责任重大，将来不管在哪个岗位上，作为社会的哪一个组成部分，我们都当时刻牢记，今天强大的中国，是党带领中国人民打下来的，我们作为共产党员，要从党的奋斗征程中不断汲取奋进力量，坚守初心、行路致远、筑梦未来。二、对照党史学习教育目标要求自身存在的差距和不足一是学习上缺乏钻研精神。虽然一直坚持终身学习的理念，明白不进则退的道理，在学习上也花了不少时间和精力，但却存在着“实用主义”“短视效应”等问题，难以沉下心来深入研读党的创新理论和深邃内涵，导致学得不成体系，没有章法，很难用好“金钥匙”指导工作。二是思想上缺乏斗争精神。互联网时代，海量信息泥沙俱下，真假难辨。自己在大事大非面前旗帜鲜明、立场坚定。但对一些发生在自己身边或者在网络上看到的不良现象，存在“事不关己、高高挂起”的思想，理直气壮、据理力争的勇气不够，缺乏斗争精神。三是工作上缺乏进取精神。工作中缺乏激情，不能始终保持昂扬的精神和奋斗的姿态。在履职尽责和为群众服务方面，存在一定的惰性，有时候会满足于工作完成就好，效率和质量没有严格要求，没有发挥好党员先锋模范作用。三、下一步的努力方向和改进措施一要加强理论学习。坚持把深入学习贯彻习近平新时代中国特色社会主义思想作为提高理论水平和党性修养的首要任务，深入学习党史和党的创新理论知识，在学懂弄通做实上再下苦功夫。二要严守党的规矩。始终保持清醒坚定的政治立场，在政治上讲忠诚、在组织上讲纪律、在行动上讲原则，始终站在党的立场上想问题、办事情，让“两个维护”真正成为内化于心，外化于行的行动自觉。三要改进工作作风。多向身边的领导同事学习，不断提高责任感，增强事业心，防止和克服麻痹懈怠的思想，认真履职尽责，在其位，谋其政。以上是我个人的检视发言，敬请同志们批评指正。
