新時代大學生價值觀之我見

#+author: 吳歌 196001723

我認爲 =價值觀= 是衡量事物價值的視角。
* 尊重別人的腳
# 美國人經常提一個美國夢是吧，核心其實就是給青年人一個盼頭


#+begin_quote 任正非
在我們這社會，聰明的人太多，往往精緻而利己，
而社會不需要這麼多聰明的人，而需要更多的阿甘。
#+end_quote
但是那時候的通信可賺的*爆炸。

=爲什麼= ？
如果各位有刷各類平臺（比如豆瓣/知乎/微博等），相信一定對討伐996的聲潮有所印象，
一個個喊得轟天響，看得人是熱血沸騰，但現實是大傢伙一個接着一個往大城市裏衝鋒，嘴巴朝着後面說，腿向着前面跑。
看看寧波，深圳，杭州等這些城市的樣子，都是 =用腳投票= 的結果，
再看看比日本還低的生育率，也是 =用腳投票= 的結果，這個數據更有趣的一點其實是，宏觀越廣，微觀越失真，
我家在的小縣城的二胎率絕對不低，新開而人不少的幼兒園不罕見，可見一線城市的人不生的絕對不少。

只不過是兩批人用腳投票的區別。
不如說一個稍微尖銳一點的提問：前面一直在批判”精緻利己主義者“的人，以後打算結婚嗎，打算生幾個小孩呢？
小孩=大量消費，讓你掏錢可厲害多了，長大點還可以是標準的人口紅利。
所有阻礙別人自私並扣上一個“精緻利己主義者”帽子的人，不如說才是自私的人，因爲自私不丟人，損人利己才丟人。
倒牛奶就是一個很好笑的例子，誰負責分發，出事了誰負責，成本轉嫁給誰呢？
更自私的人大概是，仗着自己祖輩和父輩的積累，去當好人，
然後要求沒積累的人去當聖人。
#+begin_quote
窮則獨善其身，達則兼善天下。
#+end_quote
希望大家都能明白這個詞。

* 支持更廣的“成功”觀
尊重“人”的價值，更好的享受自己。


有很多好玩的例子，比如說貿易戰中暴露的系統壟斷問題，
而我們國家用來對抗壟斷的是國內維護的linux發行版，
什麼是linux？
是一群有空的程序員，在沒收入的情況下，自發互相協作維護改進一個在網絡上公開的代碼庫，最後佔據了最廣泛的服務器市場的操作系統內核，在其基礎上擴充應用層面的東西就叫linux發行版。
仔細一想，這其實是和我剛剛提的“支持用‘腳’投票是衝突的”——搞錢都來不及，怎麼有空搞這些。
這就是我們需要“更廣泛”的成功觀的來源，
你是理工科，你沒必要整啥文理科大戰的。
你是每天996賺着大錢，沒必要鄙視別人小縣城窮但有空的人，甚至還應該反思一下自己打亂了社會的正常生活節奏。

新時代大學生價值觀之我見

#+author: 吳歌 196001723

我認爲 =價值觀= 是衡量事物價值的視角。
* 尊重別人的腳
# 美國人經常提一個美國夢是吧，核心其實就是給青年人一個盼頭


#+begin_quote 任正非
在我們這社會，聰明的人太多，往往精緻而利己，
而社會不需要這麼多聰明的人，而需要更多的阿甘。
#+end_quote
但是那時候的通信可賺的*爆炸。

=爲什麼= ？
如果各位有刷各類平臺（比如豆瓣/知乎/微博等），相信一定對討伐996的聲潮有所印象，
一個個喊得轟天響，看得人是熱血沸騰，但現實是大傢伙一個接着一個往大城市裏衝鋒，嘴巴朝着後面說，腿向着前面跑。
看看寧波，深圳，杭州等這些城市的樣子，都是 =用腳投票= 的結果，
再看看比日本還低的生育率，也是 =用腳投票= 的結果，這個數據更有趣的一點其實是，宏觀越廣，微觀越失真，
我家在的小縣城的二胎率絕對不低，新開而人不少的幼兒園不罕見，可見一線城市的人不生的絕對不少。

只不過是兩批人用腳投票的區別。
不如說一個稍微尖銳一點的提問：前面一直在批判”精緻利己主義者“的人，以後打算結婚嗎，打算生幾個小孩呢？
小孩=大量消費，讓你掏錢可厲害多了，長大點還可以是標準的人口紅利。
所有阻礙別人自私並扣上一個“精緻利己主義者”帽子的人，不如說才是自私的人，因爲自私不丟人，損人利己才丟人。
倒牛奶就是一個很好笑的例子，誰負責分發，出事了誰負責，成本轉嫁給誰呢？
更自私的人大概是，仗着自己祖輩和父輩的積累，去當好人，
然後要求沒積累的人去當聖人。
#+begin_quote
窮則獨善其身，達則兼善天下。
#+end_quote
希望大家都能明白這個詞。

* 支持更廣的“成功”觀
尊重“人”的價值，更好的享受自己。


有很多好玩的例子，比如說貿易戰中暴露的系統壟斷問題，
而我們國家用來對抗壟斷的是國內維護的linux發行版，
什麼是linux？
是一群有空的程序員，在沒收入的情況下，自發互相協作維護改進一個在網絡上公開的代碼庫，最後佔據了最廣泛的服務器市場的操作系統內核，在其基礎上擴充應用層面的東西就叫linux發行版。
仔細一想，這其實是和我剛剛提的“支持用‘腳’投票是衝突的”——搞錢都來不及，怎麼有空搞這些。
這就是我們需要“更廣泛”的成功觀的來源，
你是理工科，你沒必要整啥文理科大戰的。
你是每天996賺着大錢，沒必要鄙視別人小縣城窮但有空的人，甚至還應該反思一下自己打亂了社會的正常生活節奏。


我當然不是反對有遠大的理想與規劃，有趣的事情是大家嘴裏遠大的理想和規劃都很好聽，腿都是向當人上人一路狂奔。
再進而鄙視起放棄競爭，找個小縣城默默享受自我的人。
快樂的來源變成了貶斥他人，而不是有時間享受自己。



我當然不是反對有遠大的理想與規劃，有趣的事情是大家嘴裏遠大的理想和規劃都很好聽，腿都是向當人上人一路狂奔。
再進而鄙視起放棄競爭，找個小縣城默默享受自我的人。
快樂的來源變成了貶斥他人，而不是有時間享受自己。


