* 贴吧里的stuff们
**BilibiliId:未知KK
(和奶宝不是一个人)这个人能确定的身份是超电的stf。至少负责京华和冰糖，之前还负责了阿夸的演唱会，也是勒夫线下快打事件的参与者，也与holocn事件的处理有关，还参与了这次bls。目前仅知道不是底层stf，但是具体是啥不知道.
**糖宝.森中夜鹿
不是请了几个头头去谈话了那边怎么还那么狂
nga加油啊看11月了
**殷子珺
懂得都懂

* Nanami
 (啜泣)我也不知道讲什么,我....来直播哭了
(啜泣)不知道讲什么...嗯...咳咳
我就是觉得,好那个.
因为我很久没有,很久没有看论坛了
这一天我下了之后我才...我就看了一点之后我才..是真的
我不知道为什么,就是,这么喜欢编排别人的人设.
为什么为什么大家都..都一起都是在努力,为什么要把我编排的好像什么
什么那个背景这个背景,然后我的性格怎么怎么怎么怎么
然后我一些眼熟的一些ID的人,这边在直播间内个怎么聊,内边又在其他直播间又在其他地方阴阳怪气我.
我..我算是知道了,我真的..我真的算是知道了
我真的..我最近..一直憋着..那为什么,为什么就这么误会我,为什么每个人都要这样误会我
(大哭)我... 我..平时直播我不这样子..你们都这样子..误会我..(大哭)
..我最近..就一直这样过不去 ..(大哭)
每次都是,每次都是这样子.大家都是一样的一样的很努力做这件事情
但,总有人....(大哭)
我真的觉得,自己做这些事情,自己做这些事情很没有意思知道吗..(大哭)
(大哭)........
我觉得自己做这些事情真的是很没有意义的.. (缓过来了)
为什么..为什么. .你们可以叫我可以不要看这些地方
不要在意这些..其他地方可以乱说我呀...其他地方乱说我..其他地方乱说我
其他人看了之后不明所以的就这么相信..那我就..那我应该怎么做才比较好呢
有人能告诉我么,请问,有人能告诉我么..(哭)
我自己..我又没办法哪里证明,我一有些事情..你回应了又怎么办..小号发的这个发的..
那我去哪里说这些事情..为什么我每次都要说我这个事情那个..
(哭到气短咳嗽.可爱)
我真的不懂..可是就是没有人处理这些事情呀,就让我不要理,不要回应,那..其他人就能乱说我
我反映了,我很早就反应了,但是要我不要理,我能怎么办..
然后,这样说我,那样说,说我瞧不起RUKI....RUKI自己都,自己都跟我说她觉得很搞笑..
为什么能从我们两个开玩笑的地方.能得出这个结论..而且还说..说到现在..
说我.说我瞧不起RUKI,说到现在.这个事情..我真的我都..我都我最近在干嘛,
我都..我都觉得我做什么事情,我这样做真的有意义么,我每天开开心心不好吗
没必要改变别人的想法,.不可能啊..那那些人就能就能乱我么,,但他们能改变其他人对我的想法啊..
(静默)
他们,他们从来不会来看我直播的,然后说我,说我,性格什么,说我性格那种自闭什么..都是什么说什么是心机独比
那我该,我该怎么说,,那不明所以的人看了又相信..那我该怎么办啊
(静默)
我无视了啊..我已经无视到现在了啊..
我真的..我真的不知道为什么有些人能说的跟真的一样..说的跟真的一样
说,说我我我什么很有背景什么,..我跟B站什么什么..我真的..我真的很希望是这样子..我也很希望是这样子
真的..我要是.我要是真的像他们说的那样子..
我不用现在就坐在这里哭,我不用在这里觉得很难过,我不用每天想怎么怎么直播,怎么怎么做视频,
怎么..怎么去跟其他人打交道,我不用花心思去想这些事情根本就..
(静默)
本身..本身这种东西就没办法跟什么人说的..没办法..你跟现实朋友讲.他们也不会很懂在讲什么的..
那自己号也不能发泄着东西.大号不能发泄..自己的号不能发泄...那..你让我去哪里说...你让我.. 憋住
人家.她们上午谈心..那我..我也在谈心,,我也没有说什么不好的话,,我也没针对谁..
我就是说..我就是想说一下关于自己的事情
(抽纸擦眼泪啜泣)
嗯..我能..我能说什么呀...我被..我被同事背刺的时候..我也没有.我也根本就没办法出来说什么东西
也没有人在意..那就这样吧..那我也不说..是没有什么好说的..但是.我不去说别人,我不说关于我的事情
别人就一直在乱说我,那我能怎么办啊..
那你..他们到底要怎么样才行,我不播了他们开心了是吗,,那不行..我又不能不播,又不是只为了他们播的.
本身就是..没.. (啜泣)..我这几天一直觉得没什么意思的感觉..
但是我觉得..因为真的..喜欢我的人对我真的很好..所以没有办法..肯定不能说不干就不干..
(啜泣)嗯...让我无视那些.我真的无视到现在,越讲越真的...
昨天还有人说什么原来我我是..我是什么谁谁谁的人,什么后浪什么的,什么这就是维阿吗,**逆***,
我我能说什么吗..我能说这不是这样子的.我想说这不是这样子的.我能在哪里说吗..我又不能在哪里说..
那一个人这样说,两个人这样说,三个人这样说.那就变成真的了...咳咳
我知道他不是真的,那怎么办呐.那就是有越来越多的人他不知道这不是真的啊.就是这种人就会信这种事情呐.
咳,我反正,我..我正常直播绝对不会这样子.但是我今天实在.晚上我实在是受不了..咳咳咳
哪有人..哪有人就是.我真的我对,我对有些ID,我一直,因为很早观众就在嘛.
我对他们一直是.觉得心里记着这个人,我对他们一直是怀抱善意的,但是我真的没有想到,有些人在论坛里面讲是这样子的,原来是一直是这么看待我的,一直是这样讲我的..
说什么什么..说什么什么什么..什么对我.什么你会对UZI有梁木么,什么这种话讲出来..我真的,我真的没有想到
不要..谢谢SC.但是不要,不要在这不要在这个时候..不要在这个时候打钱..咳咳
(静默)..咳咳...阿媂娅.,,咳咳...我一直激动的时候哭的时候会过呼吸的..多吸几口气就喘过了..
