* 什么是二次元？
如果我们随机采访街上群众，让它们给“二次元”一个定义，答案肯定千人干面各不相同，但绝对不会离开日本的舶来词汇。二次元的含义在国内有几重发展，从广泛指代平面动画/电视游戏，再到特定指代日本生产的相关文化产品，再到对日式风味文化产品的泛称和相关爱好者的自称。到现在，大部分大学生都能理解“你也是‘二次元’？”的词法，可见它的渗透有多么的广泛。但为了方便讨论，我们接下来将二次元的词意限定为日式风味ACGN（即anime动画，comic漫画，game游戏，novel小说）的广泛指代。
* 二次元的发展
我国的二次元文化是极具独特的特色的，从早期模仿日本的蹒跚学步，到后期资本的入场强力推动改革。资本将早期UGC（用户生产内容）风味偏重而不够商业化的小论坛一个个击碎，大量引入舶来动画并给予推广，吸引了大量消费能力有余而生产能力不足的轻度用户，[[https://www.iimedia.cn/c1061/78502.html][iimedia]]的调查数据显示，2020年中国二次元用户为3.7亿人，甚至预估在2021年会达到4.03亿人，是一片有待资本耕种的土壤。
* 资本对二次元的异化
资本的操作客观上推进了国内二次元的发展，但快速发展导致创作者极少消费者极多，创作者议价空间极大，拥有了营销消费主义的空间：比如动画或者漫画，通过饭圈管理/国产营销，将好坏产品都供成“好”的；又比如商家将为ip付费的人营销成“信仰无价”，吸引不具备消费能力的消费者在“信仰真挚度”上攀比，进而让消费者们进行无谓的消费；又比如在免费游戏内营造阶级，勾引竞争。这是网络消费主义对青年学生在二次元上消费观念和行为的影响，但国内的创作者社群和消费者群体为何沦落至此。我们接下来会仔细讨论。
* 异化的实施
消费主义异化来自：
  - 资本对二次元生产者的强掌握，资本的强掌握与国内同人文化缺失极其相关。同人，一开始指代以某作品为基础改编的非商业创作，到后来就变成指代所有在集会上不经商业发行而贩售的二次元产品，是民间创作者获得正反馈的一大来源，是一场对抗商家掌控下生产者过度营销的反抗，但已经被资本异化的青年学生不吃这一套：调查显示，在一般/较多喜欢二次元的人占总体80%的情况下，不了解同人文化的甚至是大部分。
  - 资本有意识的打压，比如通过组织一些人，利用目前很多模糊的审查条款举报并打压。又比如借着“圈地自萌”的台词，剥夺小众领域创作者在网络上任意场所推广自我的权利，使得这些领域的消费者和生产者都只能慢慢凋亡，进而被资本掌控下的大环境所捕获。
