* Circle in history
Intro
#+begin_quote
虽然有时候，这个世界看起来有点走了一个轮回，又回到起点的感觉，老的被淘汰的东西又复活了，但实际上这就是所谓螺旋式的上升，看起来是老技术的复辟，实际上是老技术被后来的技术改造后，升级成了更新更好的技术.
#+end_quote
** 什麼是更好的人機交互?
人機交互,是一门研究系统与用户之间的交互关系的学问.
說白了,就是研究怎麼用戶怎樣"更好"地向系統交流信息,
什麼是"更好"?
- 更精確
- 更快速
  從人機交互這個概念發展以來,就是在這兩者間做"我都要"的嘗試與取捨,
  之前有同學提到的寧靜技術,目標就是在超大量信息流中提供最精準的信息.
  讓我們先陳列一下常見交互方式這兩個能力的強度.
  
*** The table
#+caption: 交互
| 方式                   | 精準度 | 速度 | 學習成本 | 備註                       |
|------------------------+--------+------+----------+----------------------------|
| 實體輸入設備(譬如鍵盤) | 極高   | 慢   |          | 擅長應付"離散"的數據       |
| 鼠標/觸摸屏/寫畫板     | 高     | 快   |          | 適用範圍小                 |
| 語音                   | 中等   | 中等 |          | 甚至對口音有比較嚴苛的要求 |
|                       |        |      |          |                            |
|                        |        |      |          |                            |

*** 離散與連續
這是一個"概念",
電腦顯示器的像素是離散的,但我們會認爲鼠標給我們"連續"而精準的2d輸入和定位能力,
比如說圖像編輯或者建模,比如說遊戲時把射擊指針對準別人.
而文本處理,打開程序(=這裏要解釋爲什麼=),選擇窗口
但"連續"已經被濫用了,比如你希望打開一個文件瀏覽器
爲什麼你需要把指針劃過一個曲線,移到耗費了大量系統資源進行佈局計算的一個按鈕上,而不是簡單地通過模糊搜索打開這個文件呢?
這裏起決定性的交互動作反而是離散的鼠標點擊,而不是劃過的弧線.

** 迴旋的發展                                                                                      
但從歷史的發展角度來看,正是被"濫用"的鼠標戰勝了鍵盤,讓全人來從黑漆漆的終端界面大跨步到可以點點點的圖形交互界面.
這正證明了鼠標比之鍵盤的強大之處.
確切地說,這證明了"當時"鼠標確實比鍵盤易用且強大,
這是當時的終端界面,沒有補全,沒有
#+end_quote

我們接下來就用wps和office的故事來舉個例子吧

=Do we really need this?= 首先這對手腕不友好,其次...

** OLD STORY
這是dos時代wps和office的樣子,你可能很難想象文字塊進行編輯都需要按下標記開始快捷鍵,然後用方向鍵把光標移到需要的位置,再通過鍵盤快捷鍵來複製粘貼.
=圖片 * 2=
又或者是標記一個標題用的是專用的標記符號,表格還需要繁雜的製表符才能建立,只有通過打印模擬才能看到最後排版的效果.
而那時候電腦的機能又很爛,那wps被所見即所得的microsoft word擊敗也是理所應當的
=圖片=











** 人机交互的发展历史


- 拼音輸入法 =可能不合適=



=來源=
#+begin_quote
Office 当年为何击败了 DOS 版 WPS 却未能击败同样非所见即所得的 TeX 系？ - 刘一的回答 - 知乎
https://www.zhihu.com/question/325608428/answer/727287753

最后就是计算机性能在这三十年也是突飞猛进的发展，现在Tex已经可以轻易实现实时渲染，使用者可以快速方便的看到效果并进行调整，而当年的计算机性能是无法做到这一切的，全部要靠打印模拟功能才行，当然打印模拟也没有现在这么快这么好用，调整就变成了一场噩梦.
虽然有时候这个世界看起来有点走了一个轮回，又回到起点的感觉，老的被淘汰的东西又复活了，但实际上这就是所谓螺旋式的上升，看起来是老技术的复辟，实际上是老技术被后来的技术改造后，升级成了更新更好的技术例如，
很多年轻人可能都会对八九十年代无数人研究汉字编码，对五笔、郑码、认知码这些形码输入法的风靡一时无法理解，他们会好奇为什么这么多人非要研究出一个新的输入法来代替现在已经非常好用的拼音。事实是，我们现在的拼音输入法是从最古老的原始的全拼输入法，经过了智能ABC、微软拼音、紫光拼音、拼音加加等诸多输入法十多年的进化，最终在搜狗输入法完善的。最早的全拼输入法既没有词语输入也没有整句输入，连简拼、智能组词、自学习词语和自动词频调整都没有，词语只有库里那点，不认识的生僻字只能去翻字典，我相信现在人去用这输入法肯定是会抓狂的，再加上当年中年人拼音教学一直很落后，也无怪乎当年那么多人都要去搞形码输入法了。幸好也有无数人没有放弃拼音输入法，拼了命的进行优化调整，很多我们已经极其熟悉的特性也在当年出现并完善，最终在搜狗这里集大成。所以也可以说，我们现在的拼音输入法，和二三十年前的拼音输入法也已经是完全不同的存在了
#+end_quote
