* Circle in history
** 输入法 例子
身边认识的用型码的人
最早的全拼输入法既没有词语输入也没有整句输入，连简拼、智能组词、自学习词语和自动词频调整都没有，词语只有库里那点，不认识的生僻字只能去翻字典，我相信现在人去用这输入法肯定是会抓狂的，再加上当年中年人拼音教学一直很落后，也无怪乎当年那么多人都要去搞形码输入法了。

** Intro
#+begin_quote
虽然有时候，这个世界看起来有点走了一个轮回，又回到起点的感觉，老的被淘汰的东西又复活了，但实际上这就是所谓螺旋式的上升，看起来是老技术的复辟，实际上是老技术被后来的技术改造后，升级成了更新更好的技术.
#+end_quote


** 什麼是更好的人機交互?
人机交互,是一门研究系统与用户之间的交互关系的学问.
说白了,就是研究怎么用户怎样"更好"地向系统交流信息,
什么是"更好"?
- 更精确
- 更快速

  从人机交互这个概念发展以来,就是在这两者间做"我都要"的尝试与取舍,
  之前有同学提到的宁静技术,目标就是在超大量信息流中提供最精准的信息.
  让我们先陈列一下常见交互方式这两个能力的强弱.

  
*** The table
#+caption: 交互
| 方式                   | 精准度 | 速度 | 学习成本 | 备注                       |
|------------------------+--------+------+----------+----------------------------|
| 实体输入设备(譬如键盘) | 极高   | 慢   | ?        | 擅长应付"离散"的数据       |
| 鼠标/触摸屏/写画板     | 高     | 快   | ?        | 适用范围小                 |
| 语音                   | 中等   | 中等 | ?        | 甚至对口音有比较严苛的要求 |
| 手势                   | 中等   | 中等 | ？       | 需要额外设备支持               |


*** 離散與連續
这是一个"概念",
电脑显示器的像素是离散的,但我们会认为鼠标给我们"连续"而精准的2d输入和定位能力,
比如说图像编辑或者建模,比如说游戏时把射击指针对准别人.
而文本处理,打开程序(=这里要解释为什么=),选择窗口都是离散的操作。
但"连续"已经被滥用了,比如你希望打开一个文件浏览器
为什么你需要把指针划过一个曲线,移到耗费了大量系统资源进行布局计算的一个按钮上,而不是简单地通过模糊搜索打开这个文件呢?
这里起决定性的交互动作反而是离散的鼠标点击,而不是划过的弧线.


** 迴旋的發展                                                                                      
但從歷史的發展角度來看,正是被"濫用"的鼠標戰勝了鍵盤,讓全人來從黑漆漆的終端界面大跨步到可以點點點的圖形交互界面.
這正證明了鼠標比之鍵盤的強大之處.
確切地說,這證明了"當時"鼠標確實比鍵盤易用且強大,
這是當時的終端界面,沒有補全,沒有高亮，无法查询历史纪录
#+end_quote

我們接下來就用wps和office的故事來舉個例子吧

=Do we really need this?= 首先這對手腕不友好,其次...

** OLD STORY
可以看到，在键盘时代，你
這是dos時代wps的樣子,你可能很難想象文字塊進行編輯都需要按下標記開始快捷鍵,然後用方向鍵把光標移到需要的位置,再通過鍵盤快捷鍵來複製粘貼以及……更改格式(通过各种标记符号),
你甚至不能用Shift+方向键来进行快速选择.
而与之对比的office则是有着所见即所得的强大体验，和鼠标带来的便利选取编辑（wps需要打印模拟才行,而这行为很耗费时间）
很显然这里的人机交互可用性已经是有代差了，那wps被office打的找不着北（当然也有盗版的因素）是再合理不过的事情.
到现在了,在学术界,更古老的latex反而在缓缓复兴,他跟古老的wps一样用标记符号来标记区块,打印也需要预览才能打印,
但伴随着编辑器的发展(提供强大的补全)和电脑性能的发展(提供即时预览->也就是可见即所得)让他的很多问题不再是问题,
反而突出了更多优点
1. 强硬规定树状结构,子树是规整的,比起word类软件段和段之间仅有文字的区别(也导致你想切换段落层级的时候会在格式刷上被折磨很久)
2. 完整的公式符号系统,比word层叠的散列易编辑易观察


八九十年代无数人研究汉字编码，对五笔、郑码、认知码这些形码输入法的风靡一时无法理解，他们会好奇为什么这么多人非要研究出一个新的输入法来代替现在已经非常好用的拼音。事实是，我们现在的拼音输入法是从最古老的原始的全拼输入法，经过了智能ABC、微软拼音、紫光拼音、拼音加加等诸多输入法十多年的进化，最终在搜狗输入法完善的。最早的全拼输入法既没有词语输入也没有整句输入，连简拼、智能组词、自学习词语和自动词频调整都没有，词语只有库里那点，不认识的生僻字只能去翻字典，我相信现在人去用这输入法肯定是会抓狂的，再加上当年中年人拼音教学一直很落后，也无怪乎当年那么多人都要去搞形码输入法了。幸好也有无数人没有放弃拼音输入法，拼了命的进行优化调整，很多我们已经极其熟悉的特性也在当年出现并完善，最终在搜狗这里集大成。所以也可以说，我们现在的拼音输入法，和二三十年前的拼音输入法也已经是完全不同的存在了










** 人机交互的发展历史


- 拼音輸入法 =可能不合適=



=來源=
#+begin_quote
Office 当年为何击败了 DOS 版 WPS 却未能击败同样非所见即所得的 TeX 系？ - 刘一的回答 - 知乎
https://www.zhihu.com/question/325608428/answer/727287753

最后就是计算机性能在这三十年也是突飞猛进的发展，现在Tex已经可以轻易实现实时渲染，使用者可以快速方便的看到效果并进行调整，而当年的计算机性能是无法做到这一切的，全部要靠打印模拟功能才行，当然打印模拟也没有现在这么快这么好用，调整就变成了一场噩梦.
虽然有时候这个世界看起来有点走了一个轮回，又回到起点的感觉，老的被淘汰的东西又复活了，但实际上这就是所谓螺旋式的上升，看起来是老技术的复辟，实际上是老技术被后来的技术改造后，升级成了更新更好的技术例如，
很多年轻人可能都会对#+end_quote
