* l
** Description
   Severe acute respiratory syndrome (SARS), an atypical pneumonia of unknown aetiology, was recognized as a global threat in mid-March 2003. To minimize transmission to others, the best strategy is to separate the suspects from others.
   In the Not-Spreading-Your-Sickness University (NSYSU), there are many student groups. Students in the same group intercommunicate with each other frequently, and a student may join several groups. To prevent the possible transmissions of SARS, the NSYSU collects the member lists of all student groups, and makes the following rule in their standard operation procedure (SOP).
   Once a member in a group is a suspect, all members in the group are suspects.
   However, they find that it is not easy to identify all the suspects when a student is recognized as a suspect. Your job is to write a program which finds all the suspects.

   The input file contains several cases. Each test case begins with two integers n and m in a line, where n is the number of students, and m is the number of groups. You may assume that 0 < n <= 30000 and 0 <= m <= 500. Every student is numbered by a unique integer between 0 and n−1, and initially student 0 is recognized as a suspect in all the cases. This line is followed by m member lists of the groups, one line per group. Each line begins with an integer k by itself representing the number of members in the group. Following the number of members, there are k integers representing the students in this group. All the integers in a line are separated by at least one space.
   A case with n = 0 and m = 0 indicates the end of the input, and need not be processed.
** input:
   100 4
   2 1 2
   5 10 13 11 12 14
   2 0 1
   2 99 2
   200 2
   1 5
   5 1 2 3 4 5
   1 0
   0 0
** output:
   4
   1
   1

   #+begin_src C++ :file union-set.cc :cmdline 1 0
     #include <algorithm>
     #include <cstdio>
     #include <cstring>
     #include <iostream>
     #include <string>
     using namespace std;
     int numOfMembersInSet[10000]{0};
     int theSet[10000]{0};
     void setInit(int num) {
       for (int circle = 0; circle < num; circle++) {
         // assume that every set is independent
         theSet[circle] = circle;
         numOfMembersInSet[circle] = 1;
       }
     }

     int rootOfSet(int Set) {
       // check if the set have non parent set
       if (theSet[Set] != Set)
         theSet[Set] = rootOfSet(theSet[Set]);
       return theSet[Set];
     }

     int mergeSet(int parent, int child) {
       auto parentSet = rootOfSet(parent);
       auto childSet = rootOfSet(child);
       /**
        ,* every childSet belongs to itself
        ,*/
       if (parentSet != childSet) {
         // set childSet's parentSet
         theSet[childSet] = parentSet;
         // add the number of members to sums
         numOfMembersInSet[parentSet] += numOfMembersInSet[childSet];
       }
       return 0;
     }

     //✌ ✌✌ ✌✌ ✌ ✌ ✌ ✌ ✌ ✌ ✌ ✌ ✌ ✌ ✌ ✌ ✌ ✌ ✌ ✌
     int main() {
       int m, n;
       while (std::scanf("%d%d", &n, &m) != EOF) {
         if (n == 0 && m == 0)
           break;
         setInit(n);
         while (m--) {
           int parSet, chSet, numOfInput;
           std::scanf("%d", &numOfInput);
           std::scanf("%d", &parSet);
           numOfInput -= 1;
           while (numOfInput--) {
             scanf("%d", &chSet);
             mergeSet(parSet, chSet);
           }
         }
         std::printf("%d\n", numOfMembersInSet[rootOfSet(0)]);
       }
     }
   #+end_src

   #+RESULTS:
