TODO:买一个60%+F区的键盘

* 一些能力
不说基础能力
- 扔下眼前利益:比如说一美元拍卖陷阱
- 敬畏 **客观事实** 所有人都知道内卷不太对路,但骂起来是没有用的.你唯一能选择的是 **不玩**,用脚投票.
- 观察别人怎么用脚投票的,嘴皮子不具备任何参考价值
- 不是不努力,朝 **好的赛道** 努力
- 如果todo清不完,证明上todo的事情重要程度有问题.
- 不存在不紧急但是有deadline的事情


* 公平就是让干坏事的人掉脑掉，效率就是多挣钱，这决定了所有制，干坏事的人肯定会支持后者，挣不到钱的人肯定会支持前者，可以挣到一点小钱但是不敢做坏事的小布尔乔亚会在两者之间斡旋
* 左派负责加速,右派负责刹车
而最好的WTO初入时代结束了...

* 孔子过泰山侧 ，有妇人哭于墓者而哀，夫子式而听之，使子路问之，曰：“子之哭也，壹似重有忧者。”而曰：“然。昔者吾舅死于虎，吾夫又死焉，今吾子又死焉。”夫子曰：“何为不去也？”曰：“无苛政。”夫子曰：“小子识之：苛政猛于虎也。”

　　出自《十三经注疏》本《礼记·檀弓下》。

* What is =Free Speech=
- You can only represent yourself
- **I** can rob your freedom of Free Speech in =my= place
- But you can enjoy your Free Speech in other places.
- **I** does not includes government.
- 例子:我代表你向我道歉

* 一些冷知识点:
- 考公可以无条件解约

- 农村户口 有田 就算就业

- 无罪化!=合法,就像犯法!=犯罪一样
- 东亚模式是错误而强大的,欧美模式是正确但脆弱的.
  无限次博弈/多次博弈/单次互相无法交换信息的博弈

- 正教宣扬真善美，你去研究一百遍依然是真善美。邪教表面宣扬真善美，骨子里有另一个目的：比如推翻某一政党啦，某教领袖人物是绝对正确的啦，要捐钱，捐钱后钱物用途不公开啦！等等。

- 老实只是一种性格，一种行为习惯，而不是一种美德。
  老实!=诚实
- __国是唯一一个刺客被供奉在最高处，而圣殿骑士拥有完全掌控的国家->America
- “民为贵，社稷次之，君为轻。”
- 如果中k院和工c院自己屁股正的话，他们不可能容忍这么多中y院士、造假y士们每天在里面跳大神而不开除他们。
- 从上而下的去污除渍的能力。如果你看到一部分被标榜为“最伟大的国s无双”们在鼓吹宣传的话术包装下的精美盒子里装着大便，如果你发现他们本身也是“做最精美的包装，营销最恶臭的大便”——那么你如何敢买他们的更夸张不切实际的承诺呢？

* 感觉应该学一点的金融:
** 怎么花钱?
- 用信用卡容错的，就你们还在用存款容错。我说难听点极端点，钱都给你贷出来了，你当老赖他能枪毙你不成？
- 钱一定要拿去买资产，买的越多，越不愁钱。但是他没有说，当一个人不管怎么存钱都买不到资产的时候该怎么办。说真的，我也不知道怎么办，我只知道花掉至少还能保个本。和那些拼命存钱但是因为存得不够快的人相比，好歹你这辈子生活质量是他们好几倍。都好几倍了，是不是勉强也能算是条出路？
- 比想把商品卖给屌丝的工厂老板更恶毒的那些人，是高举反消费主义大旗让你们去存款理财买保险，增加他们贷款速度的资本游戏玩家。
- 消费应该彼此认可彼此的价值,而不是"我**才多少钱","他**就多少钱".
这样会搞得什么都不赚钱,最后利好钢筋水泥.
- 不买的正确姿势是悄悄的买替代品.
- "广泛"的消费主义只会让社会更加富有
- 税收要求有效率，一是要求征税不会损伤生产积极性，二是收税本身的成本和收上来的税相比要有效率。

- 反消费主义会有俩后果。
第一个是他的劳动力不值钱，毕竟反消费主义，但凡值点钱的劳动力都是原罪。
第二个是钱毛的速度特别快，毕竟拼命储蓄，储蓄多少，m2就可以成倍加多少。
- 印钱发给每个人，会通货膨胀。
印钱不发，钱通过银行放贷流入资本家手里。也会通货膨胀。
虽然两者都会通货膨胀，但前者穷人好歹还拿到些钱了。
还是那个例子。1个人月收入一百万，还有10个人月收入一千块。现在这个月给所有人一人发一千块，通货膨胀了1%，但穷人月收入翻倍了，赚大了。相当于损害了一点点富人是利益，补贴了穷人。
而有些穷鬼看不明白这个，他们学了个通货膨胀，以为给自己发钱是坏事，光印钱不发钱才是好事，这是典型的脑臀分离，被权贵忽悠瘸了。

- 把你扔去美国储蓄，你肯定赢，因为你和大家不一样.但这里是中国。(也就是一美元拍卖陷阱)
  


** 学习
- 重要参数 irr(内部收益率)
- 保险->反人性，反直觉 消费性>>返还型
- 很难跑赢通胀,更正确的姿势是花钱或者买农行(分红).
用信用卡抗风险更好 ; 人不一定要跑赢通胀,不然是更酷的金融陷阱.
- 投资


* 记住!
- 一管就死不管就乱的问题是出在什么都想管但人力有客观限制,不是方法问题,不行就是不行
- 地摊经济
- 可橙
- 你涨得过资产吗？
** Power
国内的种族主义者没有真的搞出事情来，并不是因为他们气焰不够嚣张，思想不够极端，只是因为我国的民众自组织能力非常之弱，完全是原子化的状态，近几年不独是种族主义，其他意识形态的拥趸同样没有搞事情的空间。但这不代表我们不应该警惕这样一股思潮，种族主义/极端民族主义在现实中无法搞事情，最根本的原因是利维坦不吃他们那一套，但是国家机器不可能完全独立于自己所处的社会环境，现在不改变，长此以往，浸淫在极端民族主义/种族主义环境中的官寮系统必然会发生畸变，到那个时候再重视怕是已经晚了。实际上，即使在现在这种高度原子化的状态下，极端民族主义/种族主义分子也不是完全搞不出事情来，从早年误把汉服当和服逼迫女孩子当众脱掉衣服，到后来的u型锁事件，再到去年山东大学学伴风波期间，有一帮种族主义流氓跑到山大女生宿舍楼下打飞机，只要一有机会右翼民粹就会露出他们的獠牙，抓住短暂的机会向无辜者施暴，已经显示出不容忽视的潜在的破坏力。

* 去做!

* 危险!
- 越不能工业化的,越应该把自己当不会上网的老年人对待:比如房子
- 手机输入法 is dangerous
- 运营商可以看到上网的时间网址和非加密数据(比如百度搜索词)并最后给出统计图,而且这些数据**完全不保密**
** 为什么所有互联网企业最后都是在搞金融呢...
*** 蚂蚁金服
SCHEDULED: <2020-11-04 Wed>
#+begin_quote
蚂蚁金服想搞高杠杆放贷有两条路子，
第一是用用户借的钱作为债券抵押去银行贷款，这样就可以用贷款来的钱继续去放贷.
第二是走资产证券化把用户借的钱变为债券再卖出去，也和第一种一样
但实际操作的时候第一种银行并不会贷款给你债券抵押一样的钱，会给你少个三分之一左右，这样就会导致这样的利润行为不会太高也无法进行下去几次
第二种会要求资产证券化提高资本金，这是巴塞尔协议的要求，也把老马给限制住了
准确来说是资产证券化时要有资本金的要求
这本质是一种高杠杆高利润的放贷行为
jack被约谈就是因为第二种，被监管发现漏洞了
可以简单理解为空手套白狼，原本借给用户1万，也就是靠收收利息。但是资产证券化可以让这一万元无数次使用，借给用户一次就能靠卖这个一万元的债券立马赚回来又接着放贷，说成是永动机也不为过.
#+end_quote
- p2p暴雷的时候奉孝赚钱吗 ?其实不赚,只是单纯金融监管缺位





- 信息量足够少,不要和你的直播抢注意力
- 机制简明,如果不简明,那得保证你的受众里了解它的够多.
- 能够引起 *激烈* 的情感表达
- 多人联动


*  house
https://zhuanlan.zhihu.com/p/161674562

许多人觉得中国人住不上大house仅仅是因为人均资源或者发展水平的问题，觉得比中国穷的国家都住不上大house，或者中国以后富了就能住上大house了，这就显得非常Naive了。今天让大家开开眼界，就算出不了国，也不妨碍在家就能看世界。我随便举几个发展水平跟中国接近或者不如中国的国家：
土耳其一大半土地都是戈壁和山地，所以实际上宜居的地方人口密度不比中国低。咱们不看他富裕的地方，看他亚洲部分，就选那个Kayseri吧，这城市我从来没听说过.土耳其一般不建独栋别墅，城市里的住房以多层住宅为主，我们随便找一条街看下住的条件跟中国三四线城市差不多吧，房子感觉还比我们的老破小要新一点，但人家绝对不会建33层的高层住宅。
墨西哥：面积197万平方公里，人口1.3亿，人均GDP10000美元。墨西哥大部分国土也是贫瘠的沙漠或者热带雨林，宜居地区人口密度一样不低我们来看看2100万人口，被火山包围的首都墨西哥城，是不是有点像北京？拉近了看就要密集恐惧了.随便看一条街.人家的首都人民比我们穷，但是就是能住上独栋？你也可以说欧美人跟我们文化不同，那我们再来看一个东亚的。
菲律宾：面积30万平方公里，人口一个亿，人均GDP3500美元。随便选一个城市，就那个Davao吧，杜特尔特之前当市长的地方地点就选机场附近吧，有钱人不可能住在机场边上.随便选一条街看看街景虽然破了点，但人家真的是住独栋的吧，而且这不是农村哦，这里开车到市中心15分钟.
以上哪个国家属于资源丰富，天赋异禀，可以躺赢的？所以中国老百姓在三四线城市也住不上独栋的house，是因为穷？因为人均资源不够？

我觉得资源差距是六倍的结果，应该是同样的价钱，大明住house，我们住六层大平层，这叫差六倍。现在是在人家一套house的地皮上叠了三十层鸽子笼，结果价钱还是house的六倍，这应该叫差180倍。

* Internet Spirit
Internet spirit is to break the barrier of Information,
but mixing information with loads of shit is too easy...
True spirit dies ever and now.
互联网精神就是打破信息壁垒,但往信息里混屎实在是太简单了...

* 财政转移

** 作者：gnadali
- 马前卒曹丰泽帽子x们永远不告诉你的一件事是，最好的“社会化抚养”的地方就是学校。中国所有西部留守儿童的根本问题，不是“没有学校”，而是“他们壮年的父母在大城市打工的全部税收房租最终全部被用于建设北上广土著的学校”——他们只能可怜巴巴地等着按运分配，10%的人幸运地等到天上掉下来的财政转移建学校，90%的人只能在西部没税收没财政的非常差的学校和师资条件下读书——他们永远进不去他们爹妈纳税交房租帮房东还房贷摊平土地出让金的那些大城市学区里读书。帽子x舔着个大脸说“财政转移给你们一年4000块钱脱贫就是最大的分配”——那些没户口没买房只纳税交房租的中青年打工人的钱又被分配到了哪里？
- 入棺壬日常鼓吹“西部山区脱贫简直太伟大了，分配壬永远装瞎”——问题是西部山区的壮年劳动力的钱都去了哪里？他们消费税个税和层层筛选交给城市地方财政50%的土地问题的租金又去了哪里？这些壮年劳动力坐火车外出打工几十年，他们的孩子还在等“财政转移”施舍来的山村学校时，你压榨他们爹妈这些鼎盛时期的壮年劳动力的所有教育、医疗、社保权利凭什么不能还给他们？当然，一个城市里50%的财政收入来自于土地出让金，最终落到每个人头上就是“一平米售价7万人民币，地方财政每层每户每平米收走5万楼面价，最终平摊到租房者人头上每个鸽子笼5000人民币每月的房租”上面——既然他们交了房租，给教育这个财政大头贡献了力量，你又剥夺了他们子女上学的权利，给他们在山区建学校又显出你的“大公无私”出来——入棺壬的这种双标是不是有点太可耻了？当然入棺壬日常复读“这是海量顶级专家精确计算的结果，他们比我懂，更比你懂”、“这些房子宁可盖成化粪池都不给你住”的时候，是不会想到这些的。他们要么发现了财富密码签了MCN，要么抬旗有机会落户大城市，一边唱赞歌歌颂“扶贫成果”一边狂喷“分配壬连山区小孩的教育都不关心”。希望这些人鼓吹“自我以下人均感恩，自我以上按运分配”的时候，不要遇到自己被户籍、教育这些东西绊倒的那一天。
- Solution:
    租售同权、房产税养学区


* 可橙，山东。
- 张维为：这就是××.
* law
法律法规的模糊，或者是高压性质的政策，非常容易把被管理者推向“违法的边缘地带”，这样就造成了普遍性的“违法行为”，导致被管理者非常容易被管理者抓住把柄。然后管理者再通过选择性执法，来实现自己的主观管理目的，而且能极大地拓展自己的执法空间，使自己始终立于不败之地。
* 爹味
“爹”永远大局观，永远手握全局最优解，永远为你好、也为了家庭好。不听“爹”就是和所有人做对。
* google method
** tiezi
发信站: 北大未名站 (2010年01月15日23:52:54 星期五), 转信


原文由 hizane 发表在 Triangle 版


版主别禁我，若觉得我违反版规就转joke吧，呵呵。

http://brookswelding.com.

以下的真相，如果你有怀疑，如果你觉得其他的说法才是真的，那么请你解释这样一个事

实：


Google总部在声明退出中国之后，立刻取消了所有中国工程师访问Google代码服务器的权

限。

他们都是在上班后发现服务器的home目录进不去了。事先根本没有通知。

很多人写到一半的代码，就没法动了，要等几个礼拜之后，调动到美国才能继续写


如果Google是有预谋的撤离，为什么要采取这种手段？他完全可以让员工继续工作，做一

些善后工作。 比方说现在Google music，中国公司和美国做的是不一样的（music.goog

le.cn 和 music.google.com）现在要取消中国的music了，完全可以让中国的工程师来做

这个代码迁移的工作。


现在是中国的工程师全部带薪休假，由老外来接手善后事宜。


为什么Google突然那么不信任中国这边的团队？毕竟他们自己开发的代码，让他们自己来

做迁移肯定效率更高啊


唯一的原因就是，Google内部的技术人员中被安插了党的特务（就在Google上海办公处）


事实真相就是，这个人在受到党的派遣，应聘Google成功之后，就把Gmail的关键代码do

wn下来然后上交给了组织。


而这个组织破解gmail系统的目的就是为了获取“人权团体”的邮件，这些在Google官方

的声明都有


这样一来会暴露gmail系统的所有漏洞，而且Google官方不能承认这个事情，否则他在国

际上的声誉会大受影响。他能做的就是停止中国所有的工作，中国这边所有的工程师已经

不能登陆google的代码服务器了。然后应该会抓紧几天时间修改一部分gmail代码


其实事情就是这样简单完全是突发事件，所以Google的官方声明，你去读一读原版，写的

是很仓促的，字里行间都能读出他们最高层的震惊，就是Google 三个最高层的人临时讨

论一致决定的。如果是什么和美国政府商量好的，你觉得堂堂Google的官方声明会写的那

么潦草，一点正式文件的套路都没有？


Google撤离也不是因为互联网审查，这个当然是一件很让Google不舒服的事情，但这几年

他不也就这么忍下来了嘛


特工这次的窃密行动，使Google有面临全面破产的危险（Google官方博客也说了，牵涉到

知识产权的问题），说白了，再在中国呆下去，可能要威胁到整个公司的生存，所以才如

此仓促的把中国部门的一切工作全部停掉


所以Google一开始还说打算和中国谈判，但是今天马上就放弃谈判的打算了，因为就算政

府让步，Google也不能再留了，再留就有性命危险。也不是中国市场赚钱不赚钱的问题了

，赚这点小钱，把整个公司的性命搭进去，风险太大了


关于Google工程师访问Google代码的权限，Google对于技术人员的诚信是相当信任的。即

使是一个实习生，也可以访问99%以上的代码。 Google只有一个代码库，每个进去的人学

到的第一条开发原则就是：搜！从代码库里面尽量搜索功能相似的代码，然后给原作者发

Email。讲究这种整个公司的代码共享，才会达到有那么高的编码效率。而且Google的代

码，注释，和技术说明文档是一体的，对每一个工程师都是公开的


你可以喷我，也可以提出其他的说法，但是请你在回复之前先看完全文，然后想想自己的

说法能不能自圆其说！！


我只能说，特工你太辣手了，实在逼得人家混不下去了


补充一：

这个事情还在调查中，有一个人，他是党员，来了Google没多久，就把gmail核心代码下

载下来，而且现在这个人已经不知所踪了，这些是可以肯定的


至于他是谁指使的，我们只是猜了


这两天Google总部派人过来和中国每一个工程师喝咖啡谈话，调查是不是这个人还有同伙


同时总部在评估，这件事情造成了多少代码泄漏，哪些代码需要重写


等这些工作做完，就会开始转移中国这里的工程师（要是没有调查就转移，岂不是让别的

卧底混入美帝了嘛）


然后这个时候总部应该会给一个说法，让真相大白于天下，等再过一个月左右大家再回来

看这个帖子吧！
补充二：
算了我来说吧。
里面一共三个卧底，里面居然还有共产党支部。
里面的支部书记是国安四年前就布的局。
这个朋友本科就是交大出来的，后来去了信安部。
信安部派他会交大信安学院念计算机，天天做算法题, 毕业就进了Google。
之后发展了两个内线，其中一个内鬼暴力破决Gmail的源代码系统，
把代码偷出去给了政府。
政府主要是要监控用Gmail的反共分子。
里面不得了，居然还有国安局的党支部小组。
这个老兄拿了100万奖励，外加公务员待遇。
这帮人一下班就偷偷去陆家嘴开党支部会议。
小补充三：
google是如何发现代码被转给特工的？
除非google在每个员工的电脑上装监控软件。
要访问代码，必须登陆Google唯一的代码服务器
服务器端有你的浏览记录
现在只知道这个人是党员，他在很短时间内浏览了很多代码，而且这个人现在不见了，我
只是根据这些猜测他是上交组织了
第一攻击了很多源代码管理服务器，
第二明确地告诉你是非法弄到的。
大家再看会，我的手机就会响起了……
现在同事大部分已经开始准备离开了，少部分技术人员和法律部的会继续留下来，大家情

绪非常失落，谁也没有想到会是这么个结果
** 原文


Like many other well-known organizations, we face cyber attacks of varying degrees on a regular basis. In mid-December, we detected a highly sophisticated and targeted attack on our corporate infrastructure originating from China that resulted in the theft of intellectual property from Google. However, it soon became clear that what at first appeared to be solely a security incident--albeit a significant one--was something quite different.


如同很多其他广为人知的组织一样，我们经常遭受到不同 程度的网络攻击。在2009年12月中旬，我们探测到了一次目标非常明确，复杂程度很高的攻击，这次攻击来自中国，针对的是Google公司的基础设施， 攻击窃取了Google公司的一些信息。但是，我们很快就发现事情并非想象中那么简单，这绝不是一起单纯的安全事件——尽管已经相当严重——这是一件完全 不同的事情。


First, this attack was not just on Google. As part of our investigation we have discovered that at least twenty other large companies from a wide range of businesses--including the Internet, finance, technology, media and chemical sectors--have been similarly targeted. We are currently in the process of notifying those companies, and we are also working with the relevant U.S. authorities.


首先，这次攻击所针对的不仅仅是Google。在调查过程中我们发现，还有至少20家大型公司遭到类似的攻击，涉及互联网，金融，技术，传媒以及化学领域。我们正在通知这些公司，同时我们也在和相关美国政府机构合作。


Second, we have evidence to suggest that a primary goal of the attackers was accessing the Gmail accounts of Chinese human rights activists. Based on our investigation to date we believe their attack did not achieve that objective. Only two Gmail accounts appear to have been accessed, and that activity was limited to account information (such as the date the account was created) and subject line, rather than the content of emails themselves.



第二，我们有证据表明攻击者的主要目的是企图访问中---国---人*权*活* 动人士的Gmail帐户。基于我们现在的调查，我们确信攻击者没有达到目的。只有2个Gmail帐户看起来被访问过，而且被访问的仅仅是帐户信息（比如帐 户创建日期）以及邮件标题行，邮件的内容并没有被访问。

Third, as part of this investigation but independent of the attack on Google, we have discovered that the accounts of dozens of U.S.-, China- and Europe-based Gmail users who are advocates of human rights in China appear to have been routinely accessed by third parties. These accounts have not been accessed through any security breach at Google, but most likely via phishing scams or malware placed on the users' computers.

第三，作为调查的一部分，但与本次针对Google的攻击无关，我们发现有第三方在定期的访问美国，中国，欧洲的许多人*权*支持者的Gmail帐户。对这些帐户的访问并不是通过Google认可的方式，大多是通过钓鱼欺诈手段，以及位于用户电脑中的恶意软件进行。


We have already used information gained from this attack to make infrastructure and architectural improvements that enhance security for Google and for our users. In terms of individual users, we would advise people to deploy reputable anti-virus and anti-spyware programs on their computers, to install patches for their operating systems and to update their web browsers. Always be cautious when clicking on links appearing in instant messages and emails, or when asked to share personal information like passwords online. You can read more here about our cyber-security recommendations. People wanting to learn more about these kinds of attacks can read this U.S. government report (PDF), Nart Villeneuve's blog and this presentation on the GhostNet spying incident.

我们已经利用从这次攻击中获取的信息来改进我们的基础设施和架构，以提高安全性。对于用户来说，我们建 议大家使用专业的防毒和防间谍程序软件，及时安装操作系统不定，并及时更新网络浏览器。要谨慎点击即时消息和邮件中插入的链接，并提防公开个人信息的请 求。可以通过阅读这里来了解网络安全建议。如果想多了解这类攻击，可以阅读美国政府的报告，NartVilleneuve的博客，以及这份关于 GhostNet间谍事件的演示文档。


We have taken the unusual step of sharing information about these attacks with a broad audience not just because of the security and human rights implications of what we have unearthed, but also because this information goes to the heart of a much bigger global debate about freedom of speech. In the last two decades, China's economic reform programs and its citizens' entrepreneurial flair have lifted hundreds of millions of Chinese people out of poverty. Indeed, this great nation is at the heart of much economic progress and development in the world today.

我们已经采取 非常措施来广泛的共享这次攻击的信息，并不仅仅出于安全和人**权方面的原因，更因为这些信息关系到一个全球性的话题——言*论*自* 由。在过去的二十年中，中国的经济改革以及中国人在经济方面的才能使得亿万中国人摆脱了贫穷。的确，这个伟大的国家位于今日世界经济发展的核心。


We launched Google.cn in January 2006 in the belief that the benefits of increased access to information for people in China and a more open Internet outweighed our discomfort in agreeing to censor some results. At the time we made clear that 'we will carefully monitor conditions in China, including new laws and other restrictions on our services. If we determine that we are unable to achieve the objectives outlined we will not hesitate to reconsider our approach to China.'



我们在 2006年1月启动了Google.cn， 我们希望为中国人民提供更好的信息访问能力以及一个更开放的互联网，为了这个目标，我们愿意承受搜索结果审查给我们带来的不快。那时候，我们已经表明了一 个观点，那就是“我们会谨慎的考量中国的环境，包括新的法规以及其他对于我们服务的限制。如果我们确定无法达到我们规划的目标，我们将毫不犹豫的重新考虑 在中国的策略。”

These attacks and the surveillance they have uncovered--combined with the attempts over the past year to further limit free speech on the web--have led us to conclude that we should review the feasibility of our business operations in China. We have decided we are no longer willing to continue censoring our results on Google.cn, and so over the next few weeks we will be discussing with the Chinese government the basis on which we could operate an unfiltered search engine within the law, if at all. We recognize that this may well mean having to shut down Google.cn, and potentially our offices in China.



前文提到的攻击和监视，以及在过去一年中企图进一步限制网络言论自由的行为，已经 促使我们重新考量在中国展开我们业务的可行性。我们已经决定不再继续审查Google.cn的搜索结果，所以在接下来的几周内，我们将与中国政府讨论在什 么条件下才能允许我们提供一个不用过滤的合法的搜索引擎，如果这种搜索引擎存在的话。我们意识到这很大程度上意味着我们将关闭Google.cn，并可能 关闭我们在中国的机构。

The decision to review our business operations in China has been incredibly hard, and we know that it will have potentially far-reaching consequences. We want to make clear that this move was driven by our executives in the United States, without the knowledge or involvement of our employees in China who have worked incredibly hard to make Google.cn the success it is today. We are committed to working responsibly to resolve the very difficult issues raised.



做出重新考量我们在中国的商业运作的决定非常艰难，而且我们意识到这将导致深远的结果。我们想澄清一 点，即这个决定是由Google美国总部做出，与我们在中国的雇员无关，Google.cn取得今日的成功与中国雇员的辛勤工作密不可分。我们将努力解决 这个非常棘手的事件。
* 旧版n卡驱动
https://us.download.nvidia.com/Windows/391.01/391.01-desktop-win10-64bit-international-whql.exe
